const vagas = [
  {
    data: "2026-01-05",
    titulo: "Operador de Caixa-Atendimento",
    empresa: "Não identificada",
    cidade: "Londrina",
    descricao: "Se você é comprometido, pontual e busca uma oportunidade em um ambiente organizado e colaborativo, envie seu currículo pelo WHATSAPP",
    descricaoModal:"REQUISITOS: Ensino médio completo; Experiência em caixa/atendimento de restaurante; Capacidade de organização e agilidade; Bom relacionamento em equipe; Será um diferencial ter conhecimento no sistema Sagres.",
    whatsapp: "5543991319691",
    email: "",
    banner: "banners/opcaixa.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Churrasqueiro",
    empresa: "Gelobel",
    cidade: "Londrina",
    descricao: "Venha fazer parte do nosso time! O Churrasqueiro será responsável pelo preparo das carnes, controle dos pontos e apresentação dos pratos, sempre alinhado aos padrões de excelência da casa. Deverá ter experiência comprovada com churrasqueira a carvao. Vaga para maiores de 18 anos.",
    descricaoModal:"BENEFÍCIOS: Salário Base; Plano de Saúde; Convênio Farmácia; DayOff Aniversário; Refeição na empresa; Vale Transporte;",
    whatsapp: "5543996610197",
    email: "rh@gelobel.com.br",
    banner: "banners/gelchu.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "caixa",
    empresa: "Gelobel",
    cidade: "Londrina",
    descricao: "Procuramos alguém para trabalhar como Caixa, cuidando do atendimento no caixa, recebimentos e organização dos valores. Buscamos uma pessoa atenciosa, organizada, com boa comunicação e disponibilidade de horário. Experiência será um diferencial. Vaga para maiores de 18 anos",
    descricaoModal:"BENEFÍCIOS: Salário Base; Plano de Saúde; Convênio Farmácia; DayOff Aniversário; Refeição na empresa; Vale Transporte;",
    whatsapp: "5543996610197",
    email: "rh@gelobel.com.br",
    banner: "banners/gelcaixa.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Garçom/Garçonete",
    empresa: "Belmar - Cozinha Japonesa",
    cidade: "Londrina",
    descricao: "Procuramos Garçom Garçonete com experiência comprovada em cozinha japonesa, para atuar no atendimento ao cliente, apresentação do cardápio e serviço de mesas, seguindo os padrões da casa. Vagas para maiores de 18 anos.",
    descricaoModal:"BENEFÍCIOS: Salário Base; Plano de Saúde; Convênio Farmácia; DayOff Aniversário; Refeição na empresa; Vale Transporte;",
    whatsapp: "5543996610197",
    email: "rh@gelobel.com.br",
    banner: "banners/belmar.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Atendente de Telemarketing",
    empresa: "Empresa não identificada",
    cidade: "Rolandia",
    descricao: "Procuramos Atendente Comprometido(a), organizado(a) e com vontade de aprender, para atuar no apoio à equipe.",
    descricaoModal:"REQUISITOS: Ensino Médio completo; Experiência na área; Informática básica; Experiência com prospecção; experiência no uso de CRM.",
    whatsapp: "5543991349146",
    email: "",
    banner: "banners/telemark.jpg"
  },
   {
    data: "2026-01-05",
    titulo: "Empacotador",
    empresa: "Ativa Store",
    cidade: "Londrina",
    descricao: "Vaga para Empacotador com atuação em atendimento ao cliente e organização de embalagens. Oportunidade CLT com diversos benefícios em Londrina.",
    descricaoModal:"Requisitos: agilidade e atenção, bom relacionamento e atendimento ao cliente. Atividades: embalar produtos com cuidado e agilidade, auxiliar clientes no transporte das compras até o veículo quando necessário, organizar sacolas e materiais de embalagem, apoiar a equipe de reposição e atendimento quando preciso. Benefícios: cesta básica, cesta de limpeza, plano de saúde, plano odontológico, convênio com farmácia, convênio com a loja, convênio com faculdade, área de convivência, regime CLT e day off aniversário. Local de trabalho: Rua Rio Grande do Norte, 445 Centro Londrina PR.",
    whatsapp: "5543991367846",
    email: "curriculo@grupomp3.com.br",
    banner: "banners/ativaempac.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Atendente de Fast Food",
    empresa: "SubWay",
    cidade: "Londrina",
    descricao: "Vaga para Atendente de Fast Food no Subway com escala 12x36, salário e benefícios. Oportunidade para mulheres maiores de idade.",
    descricaoModal:"Cargo: Atendente de Fast Food. Requisitos: feminino, maior de idade. Jornada: escala 12x36. Remuneração: salário mais benefícios. Contato: envio de currículo por e-mail ou WhatsApp conforme informado pela empresa.",
    whatsapp: "5543991391333",
    email: "subwaymgalondrina@gmail.com",
    banner: "banners/subway.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Garçom",
    empresa: "Empresa não identificada",
    cidade: "Londrina",
    descricao: "Vaga para Garçom com remuneração média de R$ 3.020,00, jornada de terça a domingo e atuação na Gleba Palhano.",
    descricaoModal:"Cargo: Garçom. Remuneração média de R$ 3.020,00. Horário de trabalho das 09h30 às 18h00, de terça a domingo. Requisitos: idade mínima de 35 anos e experiência mínima de 1 ano. Contato para candidatura via WhatsApp. Localidade: Gleba Palhano.",
    whatsapp: "5511999722800",
    email: "",
    banner: "banners/garcom.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Atendente de Loja",
    empresa: "Sorveteria não identificada",
    cidade: "Arapongas",
    descricao: "Vaga para Atendente de Loja em Sorveteria - Arapongas (Centro) - Ótima oportunidade para quem busca trabalhar com atendimento ao público!",
    descricaoModal:"Requisitos: Ensino Médio completo com excelente comunicação. Experiência ou facilidade para lidar com o atendimento ao cliente. Proatividade, simpatia e organização.",
    whatsapp: "55439915997711",
    email: "valgas3007@gmail.com",
    banner: "banners/sorveteria.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Atendente de Loja",
    empresa: "Ritz Sorveteria",
    cidade: "cambé",
    descricao: "Temos Vagas! Atendente na Ritz Sorvetes em Cambé - Disponibilidade para trabalhar à noite e residir na região.",
    descricaoModal:"Escolaridade: Ensino Médio Completo. Requisitos indispensáveis: Habilidades com preparação de pratos, conhecimento em matemática básica, experiência com atendimento ao público e disponibilidade para o período noturno.",
    whatsapp: "5543991597711",
    email: "",
    banner: "banners/ritz.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Vendedora",
    empresa: "Avatim",
    cidade: "Londrina",
    descricao: "Vaga para Vendedora na unidade do Shopping Catuaí Londrina. Venha trabalhar com bem-estar e aromatização de ambientes!",
    descricaoModal:"Vaga para o Shopping Catuaí Londrina. Requisitos: Ter mais de 25 anos, Ensino Médio completo, habilidade com vendas, proatividade e dinamismo",
    whatsapp: "554333017869",
    email: "prlojasrank@gmail.com",
    banner: "banners/avatim.jpg"
  },
   {
    data: "2026-01-05",
    titulo: "Vendedora",
    empresa: "Outlet.GO",
    cidade: "Londrina",
    descricao: "Vaga de Vendedora na Outlet.Go em Londrina (Av. Winston Churchill). Início imediato com salário fixo mensal!",
    descricaoModal:"Requisitos: Experiência comprovada em vendas de qualquer segmento, boa comunicação, responsabilidade, comprometimento e proatividade. Preferência para quem mora na região norte de Londrina.",
    whatsapp: "5543984561248",
    email: "",
    banner: "banners/outlet.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Vendedora",
    empresa: "Outlet Center.BR",
    cidade: "Londrina",
    descricao: "Vaga para Vendedora na Outlet Center.br em Cambé. Oportunidade com salário fixo mensal para candidatas com experiência em vendas!",
    descricaoModal:"Requisitos: Experiência comprovada em vendas de qualquer segmento, boa comunicação, proatividade, responsabilidade e comprometimento. Perfil desejado: Sexo feminino, idade acima de 20 anos. Localização: Cambé, em frente à Coca-Cola.",
    whatsapp: "5543991713025",
    email: "",
    banner: "banners/outletc.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Operador de Caixa",
    empresa: "Max Atacadista",
    cidade: "Londrina",
    descricao: "Vaga para Operador de Caixa no Max Norte Shopping - Londrina. Faça sua carreira no Grupo Muffato com diversas oportunidades inclusive para PCD e 60+.",
    descricaoModal:"Benefícios: Assistência de saúde e odontológica, seguro de vida, clube de vantagens com descontos em farmácias, vale refeição, programas de premiação e oportunidade de carreira pela Uniffato.",
    whatsapp: "5543984220966",
    email: "",
    banner: "banners/opemufa.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Auxiliar de Produção",
    empresa: "Empresa não identiicada",
    cidade: "Ibiporã",
    descricao: "Estamos Contratando! Vaga de Auxiliar de Produção em Ibiporã/PR. Oportunidade para quem busca experiência em área industrial.",
    descricaoModal:"Atividades: Separação e conferência de produtos, abastecimento de linhas, apoio produtivo, organização (5S) e manuseio de equipamentos industriais. Requisitos: Ensino médio completo e disponibilidade de horário. Diferencial: Experiência anterior na área de produção",
    whatsapp: "5543996320137",
    email: "",
    banner: "banners/producao.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Assistente de Manutenção",
    empresa: "Empresa não identiicada",
    cidade: "Ibiporã",
    descricao: "Temos Vagas! Assistente de Manutenção em Ibiporã/PR. Buscamos profissionais organizados e proativos para apoiar rotinas industriais.",
    descricaoModal:"Atividades: Apoio em rotinas de manutenção preventiva e corretiva de máquinas industriais. Requisitos: Ensino médio completo, proatividade, boa comunicação e experiência/vivência em indústria.",
    whatsapp: "5543996320137",
    email: "",
    banner: "banners/assmanu.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Lavador de veículos",
    empresa: "Empresa não identiicada",
    cidade: "Londrina",
    descricao: "Oportunidade de Emprego para Lavador de Veículos no Shopping Catuaí. Início imediato com remuneração de R$ 2.200,00!",
    descricaoModal:"Atividades: Realizar lavagem completa de veículos (externa e interna), aplicação de produtos adequados seguindo normas de segurança, acabamento final e organização do ambiente.",
    whatsapp: "554391502191",
    email: "",
    banner: "banners/lavador.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Internista/Detalhista de Carros",
    empresa: "Empresa não identiicada",
    cidade: "Londrina",
    descricao: "Vaga para Internista/Detalhista de Carros no Shopping Catuaí. Remuneração de R$ 1.900,00 para quem tem foco em qualidade e detalhamento!",
    descricaoModal:"Requisitos: Experiência em limpeza técnica de interiores e estofados, atenção extrema aos detalhes e acabamentos. Candidato deve ser meticuloso e organizado.",
    whatsapp: "554391502191",
    email: "",
    banner: "banners/internista.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Recepcionista",
    empresa: "Empresa não identiicada",
    cidade: "Londrina",
    descricao: "Vaga aberta para Recepcionista em Lava Rápido em Londrina. Oportunidade para quem possui boa comunicação e organização!",
    descricaoModal:"Atividades: Atendimento ao cliente, recepção e organização de pedidos, controle de entrada e saída de veículos e apoio nas rotinas do caixa.",
    whatsapp: "554391502191",
    email: "",
    banner: "banners/recepcionista.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Operador de Caixa",
    empresa: "Riachuelo",
    cidade: "Londrina",
    descricao: "Procuramos um Operador(a) de Caixa comprometido e responsável",
    descricaoModal:"Requisito: ter ensini médio completo.",
    whatsapp: "5543988718073",
    email: "",
    banner: "banners/riachu.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Auxiliar de Mecânica",
    empresa: "Empresa não identificada",
    cidade: "Londrina",
    descricao: "Vagas Abertas! Auxiliar de Mecânica em Londrina (Rua Pedro Botelho de Rezende). Oportunidade com salário compatível com o mercado e início imediato.",
    descricaoModal:"Requisitos: Ensino médio completo e experiência prévia na área. Horário de trabalho: Segunda a sexta das 08:00 as 18:00 e sábado das 08:00 as 12:00.",
    whatsapp: "5543996339497",
    email: "",
    banner: "banners/auxmec.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Auxiliar de Cozinha",
    empresa: "Vegas Burger",
    cidade: "Londrina",
    descricao: "Vaga de Auxiliar de Cozinha na Vegas Burger Hamburgueria (Shopping Norte). Início imediato com escala de revezamento 6x1!",
    descricaoModal:"Informações da Vaga: 1 vaga disponível para Auxiliar de Cozinha no Shopping Norte com início imediato. Escala de revezamento 6x1 com carga horária de 7:20h (turno das 14:40 às 23:00). Seleção presencial no dia 09 de Janeiro de 2026.",
    whatsapp: "5543933383030",
    email: "",
    banner: "banners/vegas.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Caixa",
    empresa: "Vegas Burger",
    cidade: "Londrina",
    descricao: "🍔 Vaga para Caixa na Vegas Burger Hamburgueria (Shopping Norte). Início imediato com escala 6x1 e ótimo ambiente de trabalho!",
    descricaoModal:"Informações da Vaga: 1 vaga disponível para o cargo de Caixa no Shopping Norte com início imediato. Escala de revezamento 6x1 com carga horária de 7:20h (turno das 14:40 às 23:00).",
    whatsapp: "5543933383030",
    email: "",
    banner: "banners/vegascx.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Atendente",
    empresa: "Gelaboca",
    cidade: "Londrina",
    descricao: "Vaga de Atendente na Gela Boca - Salário de R$ 2.500,00 + Benefícios. Venha fazer parte do time mais gelado e divertido da cidade!",
    descricaoModal:"Benefícios e Informações: Salário de R$ 2.500,00, Vale transporte, Vale alimentação e Bônus por desempenho. Se você se identificou com a vaga, mande seu currículo agora mesmo!",
    whatsapp: "5543999127431",
    email: "",
    banner: "banners/gelaboca.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Auxiliar de Limpeza",
    empresa: "Beta Serv",
    cidade: "Londrina",
    descricao: "Temos Vaga! Auxiliar de Limpeza na Beta Serv. Oportunidade para profissionais com experiência mínima na área e disponibilidade de horário.",
    descricaoModal:"Requisitos: Experiência mínima comprovada na função. Horário: Jornada semanal de 8h com necessidade de disponibilidade para trabalhar também aos fins de semana intercalados.",
    whatsapp: "5543988256040",
    email: "",
    banner: "banners/beta.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Zelador",
    empresa: "Beta Serv",
    cidade: "Londrina",
    descricao: "Temos Vaga! Oportunidade para Zelador na Beta Serv com experiência em manutenção geral e limpeza. Envie seu currículo!",
    descricaoModal:"Requisitos: Experiência comprovada em rotinas de hidráulica, elétrica e limpeza em geral. Perfil proativo e responsável para manutenção predial.",
    whatsapp: "5543988256040",
    email: "",
    banner: "banners/betazel.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Porteiro",
    empresa: "Beta Serv",
    cidade: "Londrina",
    descricao: "Temos Vagas! Oportunidade para Porteiro na Beta Serv com escala 12x36 (diurna ou noturna). Envie seu currículo agora!",
    descricaoModal:"Requisitos: Experiência mínima de 6 meses em portaria, conhecimento em informática e disponibilidade total de horário. Escala de trabalho: 12x36 para turnos diurnos e noturnos.",
    whatsapp: "5543988256040",
    email: "",
    banner: "banners/betaport.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Auxiliar de Produção",
    empresa: "Empresa não identificada",
    cidade: "Maringá",
    descricao: "Indústria contrata Auxiliar de Produção em Maringá. Salário de R$ 2.200,00 + Benefícios e horário fixo de segunda a sexta!",
    descricaoModal:"Horário: 07h às 17h (seg. a sexta) com 1h de almoço e café da manhã incluso. Salário: 2.200,00 + VT + Auxílio alimentação 200,00. Requisitos: Ser comprometido, rápido e dinâmico. Diferencial: Ter locomoção própria ou morar perto (Final da Av. Kakogawa). Obs: Vaga exclusiva para residentes em Maringá com 5 dias de teste. Contato: Carlos (44) 9 9871-1167.",
    whatsapp: "5544998711167",
    email: "",
    banner: "banners/industria.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Vendedor(a)",
    empresa: "Uso Essencial Case",
    cidade: "Maringá",
    descricao: "Vaga para Vendedor(a) na Uso Essencial (Shopping Catuaí Maringá). Salário piso shopping + comissão, prêmios e carga horária de 6h/dia!",
    descricaoModal:"Informações da Vaga: Oportunidade para Vendedor(a) na unidade do Shopping Catuaí Maringá. Oferecemos salário piso shopping, comissão, vale alimentação, vale transporte e prêmios.",
    whatsapp: "5544991496055",
    email: "",
    banner: "banners/uso.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Cozinheira",
    empresa: "JL Pizzaria e Costelaria",
    cidade: "Maringá",
    descricao: "JL Pizzaria e Costelaria contrata Cozinheiras para turnos da manhã e noite em Maringá (Vila Morangueira). Escala 6x1 com salário e benefícios!",
    descricaoModal:"Turno Manhã (08:00 às 16:00) e Turno Noite (16:00 às 00:00). Requisitos: Experiência em cozinha (desejável como cozinheira), saber fazer frituras, montagem de buffet e organização geral. Para o turno da noite, é necessário veículo próprio ou morar próximo.",
    whatsapp: "5544999978523",
    email: "",
    banner: "banners/jl.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Saladeira",
    empresa: "Empresa não identificada",
    cidade: "Maringá",
    descricao: "Vaga para Saladeira com experiência em buffet e preparo de doces. Registro CLT, salário + bonificações e ótima localização em Maringá!",
    descricaoModal:"Atividades e Requisitos: Preparar pratos e sobremesas para buffet conforme receitas, manipular alimentos e realizar cortes decorativos de saladas. Necessário experiência em carteira.",
    whatsapp: "5544999978523",
    email: "",
    banner: "banners/salada.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Atendente/Serviços Gerais",
    empresa: "Empresa não identificada",
    cidade: "Maringá",
    descricao: "Oportunidade CLT para Atendente/Serviços Gerais em Maringá (Vila Morangueira). Salário de R$ 2.500,00 + Benefícios e almoço no local!",
    descricaoModal:"Detalhes da Vaga: Regime CLT com escala 6x1 (segunda a domingo) no horário das 08:00 às 16:00, incluindo 40 minutos de intervalo e almoço no local. Requisitos: Saber montar marmitas. Salário: R$ 2.500,00 + Benefícios.",
    whatsapp: "5544999978523",
    email: "",
    banner: "banners/azul.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Motorista entregador",
    empresa: "Brasil Limp",
    cidade: "Maringá",
    descricao: "A Brasillimp contrata Motorista Entregador para atuar em Maringá e região. Necessário CNH C e disponibilidade para viagens!",
    descricaoModal:"Requisitos: Possuir CNH C e ser responsável. Atividades: Realizar entregas em Maringá e toda a região, com disponibilidade total para viagens.",
    whatsapp: "5544991024432",
    email: "brasillimp.fg@rotmail.com",
    banner: "banners/bralimp.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Auxiliar de Produção",
    empresa: "LukPaper",
    cidade: "Maringá",
    descricao: "Vaga Aberta! A Lukpaper contrata Auxiliar de Produção para fabricação de papel toalha e higiênico. Trabalho de segunda a sexta com início imediato!",
    descricaoModal:"Requisitos e Detalhes: Experiência na área, perfil responsável, pontual, organizado e com vontade de aprender. Atividades voltadas à fabricação de papel toalha e higiênico.",
    whatsapp: "5544991024432",
    email: "brasillimp.fg@rotmail.com",
    banner: "banners/luk.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Servente de Limpeza",
    empresa: "Empresa não identificada",
    cidade: "Maringá",
    descricao: "Oportunidade para Maringá! Contrata-se Servente de Limpeza com experiência para atuação em condomínio. Início imediato com salário de R$ 1.764,00 e ótimos benefícios!",
    descricaoModal:"Informações e Benefícios: Salário de R$ 1.764,00, Vale alimentação de R$ 805,00, Assiduidade de R$ 250,00 e Vale transporte. Horário: Segunda a sexta das 08h às 17h, sábado ou domingo (alternado) das 08h às 12h, com 1h de almoço.",
    whatsapp: "5543991597030",
    email: "",
    banner: "banners/servo.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Área de vendas",
    empresa: "Be Make",
    cidade: "Maringá",
    descricao: "Trabalhe na Be Make em Maringá! Vaga aberta para a área de vendas na Avenida Brasil (Zona 1). Salário compatível com o mercado e diversos benefícios inclusos!",
    descricaoModal:"Requisitos e Benefícios: Procuramos profissional empática, solícita, comunicativa, proativa, organizada, gentil, paciente e determinada. Oferecemos salário compatível com o comércio local, Vale Transporte, Vale Alimentação e Auxílio Saúde.",
    whatsapp: "5544991007320",
    email: "",
    banner: "banners/bemake.jpeg"
  },
   {
    data: "2026-01-05",
    titulo: "Área de Produção",
    empresa: "Infinity Carnes",
    cidade: "Maringá",
    descricao: "Faça parte da nossa equipe! A Infinity Carnes em Maringá está com vagas abertas para o setor de Produção com excelente remuneração e horário comercial.",
    descricaoModal:"Detalhes da Vaga: Oportunidade para o setor de Produção na Infinity Carnes. Horário de trabalho: Segunda a Sábado em horário comercial. Oferecemos excelente remuneração.",
    whatsapp: "554432293659",
    email: "",
    banner: "banners/carne.jpeg"
  },
  {
    data: "2026-01-05",
    titulo: "Operador de Loja",
    empresa: "Spoleto",
    cidade: "Maringá",
    descricao: "Vaga de Operador de Loja (Spoleto) no Shopping Catuaí Maringá. Salário de R$ 1.980,00 (Efetivado) + Vale Alimentação de R$ 400,00 e bônus por assiduidade!",
    descricaoModal:"Atividades: Atendimento ao cliente, montagem e preparo de pratos, operação de caixa, limpeza e organização da loja, além de cumprir normas de segurança alimentar.",
    whatsapp: "5544991163010",
    email: "",
    banner: "banners/spol.jpeg"
  },
   {
    data: "2026-01-05",
    titulo: "Vendedor(a) Interno",
    empresa: "VIVO",
    cidade: "Maringá",
    descricao: "A Vivo Empresas está contratando Vendedor(a) Interno! Regime CLT com salário fixo, bonificações, comissões e trabalho de segunda a sexta-feira.",
    descricaoModal:"Benefícios e Horário: Oferecemos salário fixo, bonificação, comissão, vale alimentação, vale transporte e regime CLT. O horário de trabalho é de segunda a sexta-feira, das 09h às 17:45h.",
    whatsapp: "5543999812464",
    email: "",
    banner: "banners/vivo.jpeg"
  },
  {
    data: "2026-01-05",
    titulo: "Auxiliar de Expedição",
    empresa: "Ativa Express",
    cidade: "Maringá",
    descricao: "Vaga para Auxiliar de Expedição na Ativa Express em Maringá! Salário de R$ 1.848,89 + Benefícios. Não exigimos experiência anterior, venha conferir!",
    descricaoModal:"Informações da Vaga: Atuação em empresa do ramo de distribuição de encomendas com vínculo efetivo. Horário: Segunda a Sábado das 13:00 às 22:00 (com 1h de intervalo) e disponibilidade para escala aos domingos.",
    whatsapp: "5543988418630",
    email: "",
    banner: "banners/ativaex.jpeg"
  },
  {
    data: "2026-01-05",
    titulo: "Camareira",
    empresa: "Hotel Thomasi Maringá",
    cidade: "Maringá",
    descricao: "O Hotel Thomasi Maringá está contratando Camareira! Oportunidade para profissionais proativas e responsáveis com horário de trabalho fixo.",
    descricaoModal:"Requisitos e Informações: Buscamos profissionais com proatividade, responsabilidade e boa comunicação.",
    whatsapp: "554430320400",
    email: "financeiro@hotelthomasi.com.br",
    banner: "banners/cama.jpeg"
  },
  {
    data: "2026-01-05",
    titulo: "Conferente",
    empresa: "Hotel Thomasi Maringá",
    cidade: "Maringá",
    descricao: "Oportunidade no Hotel Thomasi Maringá! Vaga para Conferente com horário comercial de segunda a sábado. Venha fazer parte da nossa equipe!",
    descricaoModal:"Informações da Vaga: Horário de trabalho das 08h às 17h durante a semana e aos sábados das 08h às 12h. Local: Avenida Colombo, 3531.",
    whatsapp: "554430320400",
    email: "financeiro@hotelthomasi.com.br",
    banner: "banners/confe.jpeg"
  },
  {
    data: "2026-01-05",
    titulo: "Motorista Entregador",
    empresa: "Ativa Express",
    cidade: "Maringá",
    descricao: "Vaga para Motorista Entregador na Ativa Express em Maringá! Salário de R$ 2.133,68 + Benefícios. Necessário CNH D com EAR e disponibilidade de escala.",
    descricaoModal:"Informações da Vaga: Atuação em empresa de distribuição de encomendas com vínculo efetivo; Requisitos: CNH categoria D com EAR. Remuneração: Salário de R$ 2.133,68, vale refeição de R$ 27,33/dia, vale transporte e horas extras.",
    whatsapp: "5543988418630",
    email: "",
    banner: "banners/ativamot.jpeg"
  },
  {
    data: "2026-01-05",
    titulo: "Ajudante de Motorista",
    empresa: "Ativa Express",
    cidade: "Maringá",
    descricao: "Vaga para Ajudante de Motorista na Ativa Express em Maringá! Salário de R$ 1.848,89 + Benefícios, com horário fixo de segunda a sábado e vínculo efetivo.",
    descricaoModal:"Informações da Vaga: Atuação em empresa do ramo de distribuição de encomendas com vínculo efetivo",
    whatsapp: "5543988418630",
    email: "",
    banner: "banners/ativamot.jpeg"
  },
  {
    data: "2026-01-05",
    titulo: "atendente de Caixa",
    empresa: "Padaria Doce Família",
    cidade: "Maringá",
    descricao: "A Padaria Doce Família em Maringá contrata Caixa Atendente! Vaga com diversos benefícios, incluindo vale alimentação, lanche no local e descontos exclusivos.",
    descricaoModal:"Atividades e Requisitos: Responsável pela abertura/fechamento de caixa, registro de vendas e apoio à equipe. Necessário experiência comprovada como caixa, agilidade, boa comunicação e conhecimento em PDV/informática.",
    whatsapp: "554432268004",
    email: "",
    banner: "banners/doce.jpeg"
  },
  {
    data: "2026-01-05",
    titulo: "Lavador Autimotivo",
    empresa: "BRANELO",
    cidade: "Londrina",
    descricao: "A rede de estética automotiva Branello contrata Lavador Automotivo para Londrina/PR. Interessados devem enviar currículo via WhatsApp!",
    descricaoModal:"Oportunidade para Lavador Automotivo na rede Branello em Londrina/PR. Se você ficou interessado(a), envie seu currículo diretamente para o WhatsApp",
    whatsapp: "5543996476306",
    email: "",
    banner: "banners/branelo.jpeg"
  },
  {
    data: "2026-01-05",
    titulo: "Telemarketing",
    empresa: "MIDAS Telecom",
    cidade: "Londrina",
    descricao: "A Midas Telecom está com vagas para Telemarketing! Oferecemos salário fixo, comissões de até 300% e benefícios para atuação em vendas externas B2B.",
    descricaoModal:"Informações e Requisitos: Atuação externa com foco em vendas de produtos TIM B2B. Buscamos profissionais com foco em resultados e domínio em negociações. É necessário possuir notebook próprio.",
    whatsapp: "5543991380246",
    email: "",
    banner: "banners/midas.jpeg"
  },
  {
    data: "2026-01-05",
    titulo: "Atendente de Restaurante",
    empresa: "Mania de Churrasco",
    cidade: "Londrina",
    descricao: "A Mania de Churrasco! contrata Atendente de Restaurante para o Shopping Catuaí e Shopping Boulevard! Vaga com plano de carreira e escala 6x1.",
    descricaoModal:"Informações da Vaga: Oportunidade para Atendente de Restaurante com escala 6x1. Requisitos: Disponibilidade para trabalhar aos fins de semana e feriados. Horários disponíveis: Das 08:00 às 16:00 ou das 15:00 às 23:00. Diferencial: A empresa oferece Plano de Carreira.",
    whatsapp: "5543996336116",
    email: "",
    banner: "banners/mania.jpeg"
  },
  {
    data: "2026-01-05",
    titulo: "Auxiliar de Almoxarifado",
    empresa: "Empresa Não Identificada",
    cidade: "Cambé",
    descricao: "Processo seletivo aberto para Auxiliar de Almoxarifado em Cambé e Rolândia! Salário de R$ 1.920,00 + Benefícios e horário de segunda a sexta-feira.",
    descricaoModal:"Atividades e Requisitos: Recebimento, separação de pedidos, conferência, expedição, descarga, limpeza e organização do local. Buscamos profissionais com responsabilidade, senso organizacional e agilidade (experiência na função será um diferencial).",
    whatsapp: "5543991244590",
    email: "",
    banner: "banners/almox.jpeg"
  },
  {
    data: "2026-01-05",
    titulo: "Assistente de E-commerce",
    empresa: "Empresa Não Identificada",
    cidade: "Cambé",
    descricao: "Oportunidade para Assistente de E-commerce em Cambé! Atuação com cadastro de produtos, marketplaces e suporte ao cliente. Necessário domínio em ferramentas de imagem e Excel.",
    descricaoModal:"Atividades e Requisitos: Cadastro de produtos, atualização de marketplaces, criação de anúncios, manutenção de fotos/vídeos, resposta a perguntas, monitoramento de vendas, suporte ao cliente e análise de dados. Exige-se Excel intermediário e domínio de ferramentas de manipulação de imagens.",
    whatsapp: "5543991244590",
    email: "",
    banner: "banners/commer.jpeg"
  },
];
