const vagas = [
  {
    data: "2026-01-05",
    titulo: "Operador de Caixa-Atendimento",
    empresa: "Não identificada",
    cidade: "Londrina",
    descricao: "Se você é comprometido, pontual e busca uma oportunidade em um ambiente organizado e colaborativo, envie seu currículo pelo WHATSAPP",
    descricaoModal:"REQUISITOS: Ensino médio completo; Experiência em caixa/atendimento de restaurante; Capacidade de organização e agilidade; Bom relacionamento em equipe; Será um diferencial ter conhecimento no sistema Sagres.",
    whatsapp: "5543991319691",
    email: "",
    banner: "banners/opcaixa.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Churrasqueiro",
    empresa: "Gelobel",
    cidade: "Londrina",
    descricao: "Venha fazer parte do nosso time! O Churrasqueiro será responsável pelo preparo das carnes, controle dos pontos e apresentação dos pratos, sempre alinhado aos padrões de excelência da casa. Deverá ter experiência comprovada com churrasqueira a carvao. Vaga para maiores de 18 anos.",
    descricaoModal:"BENEFÍCIOS: Salário Base; Plano de Saúde; Convênio Farmácia; DayOff Aniversário; Refeição na empresa; Vale Transporte;",
    whatsapp: "5543996610197",
    email: "rh@gelobel.com.br",
    banner: "banners/gelchu.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "caixa",
    empresa: "Gelobel",
    cidade: "Londrina",
    descricao: "Procuramos alguém para trabalhar como Caixa, cuidando do atendimento no caixa, recebimentos e organização dos valores. Buscamos uma pessoa atenciosa, organizada, com boa comunicação e disponibilidade de horário. Experiência será um diferencial. Vaga para maiores de 18 anos",
    descricaoModal:"BENEFÍCIOS: Salário Base; Plano de Saúde; Convênio Farmácia; DayOff Aniversário; Refeição na empresa; Vale Transporte;",
    whatsapp: "5543996610197",
    email: "rh@gelobel.com.br",
    banner: "banners/gelcaixa.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Garçom/Garçonete",
    empresa: "Belmar - Cozinha Japonesa",
    cidade: "Londrina",
    descricao: "Procuramos Garçom Garçonete com experiência comprovada em cozinha japonesa, para atuar no atendimento ao cliente, apresentação do cardápio e serviço de mesas, seguindo os padrões da casa. Vagas para maiores de 18 anos.",
    descricaoModal:"BENEFÍCIOS: Salário Base; Plano de Saúde; Convênio Farmácia; DayOff Aniversário; Refeição na empresa; Vale Transporte;",
    whatsapp: "5543996610197",
    email: "rh@gelobel.com.br",
    banner: "banners/belmar.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Atendente de Telemarketing",
    empresa: "Empresa não identificada",
    cidade: "Rolandia",
    descricao: "Procuramos Atendente Comprometido(a), organizado(a) e com vontade de aprender, para atuar no apoio à equipe.",
    descricaoModal:"REQUISITOS: Ensino Médio completo; Experiência na área; Informática básica; Experiência com prospecção; experiência no uso de CRM.",
    whatsapp: "5543991349146",
    email: "",
    banner: "banners/telemark.jpg"
  },
   {
    data: "2026-01-05",
    titulo: "Empacotador",
    empresa: "Ativa Store",
    cidade: "Londrina",
    descricao: "Vaga para Empacotador com atuação em atendimento ao cliente e organização de embalagens. Oportunidade CLT com diversos benefícios em Londrina.",
    descricaoModal:"Requisitos: agilidade e atenção, bom relacionamento e atendimento ao cliente. Atividades: embalar produtos com cuidado e agilidade, auxiliar clientes no transporte das compras até o veículo quando necessário, organizar sacolas e materiais de embalagem, apoiar a equipe de reposição e atendimento quando preciso. Benefícios: cesta básica, cesta de limpeza, plano de saúde, plano odontológico, convênio com farmácia, convênio com a loja, convênio com faculdade, área de convivência, regime CLT e day off aniversário. Local de trabalho: Rua Rio Grande do Norte, 445 Centro Londrina PR.",
    whatsapp: "5543991367846",
    email: "curriculo@grupomp3.com.br",
    banner: "banners/ativaempac.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Atendente de Fast Food",
    empresa: "SubWay",
    cidade: "Londrina",
    descricao: "Vaga para Atendente de Fast Food no Subway com escala 12x36, salário e benefícios. Oportunidade para mulheres maiores de idade.",
    descricaoModal:"Cargo: Atendente de Fast Food. Requisitos: feminino, maior de idade. Jornada: escala 12x36. Remuneração: salário mais benefícios. Contato: envio de currículo por e-mail ou WhatsApp conforme informado pela empresa.",
    whatsapp: "5543991391333",
    email: "subwaymgalondrina@gmail.com",
    banner: "banners/subway.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Garçom",
    empresa: "Empresa não identificada",
    cidade: "Londrina",
    descricao: "Vaga para Garçom com remuneração média de R$ 3.020,00, jornada de terça a domingo e atuação na Gleba Palhano.",
    descricaoModal:"Cargo: Garçom. Remuneração média de R$ 3.020,00. Horário de trabalho das 09h30 às 18h00, de terça a domingo. Requisitos: idade mínima de 35 anos e experiência mínima de 1 ano. Contato para candidatura via WhatsApp. Localidade: Gleba Palhano.",
    whatsapp: "5511999722800",
    email: "",
    banner: "banners/garcom.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Atendente de Loja",
    empresa: "Sorveteria não identificada",
    cidade: "Arapongas",
    descricao: "Vaga para Atendente de Loja em Sorveteria - Arapongas (Centro) - Ótima oportunidade para quem busca trabalhar com atendimento ao público!",
    descricaoModal:"Requisitos: Ensino Médio completo com excelente comunicação. Experiência ou facilidade para lidar com o atendimento ao cliente. Proatividade, simpatia e organização.",
    whatsapp: "55439915997711",
    email: "valgas3007@gmail.com",
    banner: "banners/sorveteria.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Atendente de Loja",
    empresa: "Ritz Sorveteria",
    cidade: "cambé",
    descricao: "Temos Vagas! Atendente na Ritz Sorvetes em Cambé - Disponibilidade para trabalhar à noite e residir na região.",
    descricaoModal:"Escolaridade: Ensino Médio Completo. Requisitos indispensáveis: Habilidades com preparação de pratos, conhecimento em matemática básica, experiência com atendimento ao público e disponibilidade para o período noturno.",
    whatsapp: "5543991597711",
    email: "",
    banner: "banners/ritz.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Vendedora",
    empresa: "Avatim",
    cidade: "Londrina",
    descricao: "Vaga para Vendedora na unidade do Shopping Catuaí Londrina. Venha trabalhar com bem-estar e aromatização de ambientes!",
    descricaoModal:"Vaga para o Shopping Catuaí Londrina. Requisitos: Ter mais de 25 anos, Ensino Médio completo, habilidade com vendas, proatividade e dinamismo",
    whatsapp: "554333017869",
    email: "prlojasrank@gmail.com",
    banner: "banners/avatim.jpg"
  },
   {
    data: "2026-01-05",
    titulo: "Vendedora",
    empresa: "Outlet.GO",
    cidade: "Londrina",
    descricao: "Vaga de Vendedora na Outlet.Go em Londrina (Av. Winston Churchill). Início imediato com salário fixo mensal!",
    descricaoModal:"Requisitos: Experiência comprovada em vendas de qualquer segmento, boa comunicação, responsabilidade, comprometimento e proatividade. Preferência para quem mora na região norte de Londrina.",
    whatsapp: "5543984561248",
    email: "",
    banner: "banners/outlet.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Vendedora",
    empresa: "Outlet Center.BR",
    cidade: "Londrina",
    descricao: "Vaga para Vendedora na Outlet Center.br em Cambé. Oportunidade com salário fixo mensal para candidatas com experiência em vendas!",
    descricaoModal:"Requisitos: Experiência comprovada em vendas de qualquer segmento, boa comunicação, proatividade, responsabilidade e comprometimento. Perfil desejado: Sexo feminino, idade acima de 20 anos. Localização: Cambé, em frente à Coca-Cola.",
    whatsapp: "5543991713025",
    email: "",
    banner: "banners/outletc.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Operador de Caixa",
    empresa: "Max Atacadista",
    cidade: "Londrina",
    descricao: "Vaga para Operador de Caixa no Max Norte Shopping - Londrina. Faça sua carreira no Grupo Muffato com diversas oportunidades inclusive para PCD e 60+.",
    descricaoModal:"Benefícios: Assistência de saúde e odontológica, seguro de vida, clube de vantagens com descontos em farmácias, vale refeição, programas de premiação e oportunidade de carreira pela Uniffato.",
    whatsapp: "5543984220966",
    email: "",
    banner: "banners/opemufa.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Auxiliar de Produção",
    empresa: "Empresa não identiicada",
    cidade: "Ibiporã",
    descricao: "Estamos Contratando! Vaga de Auxiliar de Produção em Ibiporã/PR. Oportunidade para quem busca experiência em área industrial.",
    descricaoModal:"Atividades: Separação e conferência de produtos, abastecimento de linhas, apoio produtivo, organização (5S) e manuseio de equipamentos industriais. Requisitos: Ensino médio completo e disponibilidade de horário. Diferencial: Experiência anterior na área de produção",
    whatsapp: "5543996320137",
    email: "",
    banner: "banners/producao.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Assistente de Manutenção",
    empresa: "Empresa não identiicada",
    cidade: "Ibiporã",
    descricao: "Temos Vagas! Assistente de Manutenção em Ibiporã/PR. Buscamos profissionais organizados e proativos para apoiar rotinas industriais.",
    descricaoModal:"Atividades: Apoio em rotinas de manutenção preventiva e corretiva de máquinas industriais. Requisitos: Ensino médio completo, proatividade, boa comunicação e experiência/vivência em indústria.",
    whatsapp: "5543996320137",
    email: "",
    banner: "banners/assmanu.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Lavador de veículos",
    empresa: "Empresa não identiicada",
    cidade: "Londrina",
    descricao: "Oportunidade de Emprego para Lavador de Veículos no Shopping Catuaí. Início imediato com remuneração de R$ 2.200,00!",
    descricaoModal:"Atividades: Realizar lavagem completa de veículos (externa e interna), aplicação de produtos adequados seguindo normas de segurança, acabamento final e organização do ambiente.",
    whatsapp: "554391502191",
    email: "",
    banner: "banners/lavador.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Internista/Detalhista de Carros",
    empresa: "Empresa não identiicada",
    cidade: "Londrina",
    descricao: "Vaga para Internista/Detalhista de Carros no Shopping Catuaí. Remuneração de R$ 1.900,00 para quem tem foco em qualidade e detalhamento!",
    descricaoModal:"Requisitos: Experiência em limpeza técnica de interiores e estofados, atenção extrema aos detalhes e acabamentos. Candidato deve ser meticuloso e organizado.",
    whatsapp: "554391502191",
    email: "",
    banner: "banners/internista.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Recepcionista",
    empresa: "Empresa não identiicada",
    cidade: "Londrina",
    descricao: "Vaga aberta para Recepcionista em Lava Rápido em Londrina. Oportunidade para quem possui boa comunicação e organização!",
    descricaoModal:"Atividades: Atendimento ao cliente, recepção e organização de pedidos, controle de entrada e saída de veículos e apoio nas rotinas do caixa.",
    whatsapp: "554391502191",
    email: "",
    banner: "banners/recepcionista.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Operador de Caixa",
    empresa: "Riachuelo",
    cidade: "Londrina",
    descricao: "Procuramos um Operador(a) de Caixa comprometido e responsável",
    descricaoModal:"Requisito: ter ensini médio completo.",
    whatsapp: "5543988718073",
    email: "",
    banner: "banners/riachu.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Auxiliar de Mecânica",
    empresa: "Empresa não identificada",
    cidade: "Londrina",
    descricao: "Vagas Abertas! Auxiliar de Mecânica em Londrina (Rua Pedro Botelho de Rezende). Oportunidade com salário compatível com o mercado e início imediato.",
    descricaoModal:"Requisitos: Ensino médio completo e experiência prévia na área. Horário de trabalho: Segunda a sexta das 08:00 as 18:00 e sábado das 08:00 as 12:00.",
    whatsapp: "5543996339497",
    email: "",
    banner: "banners/auxmec.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Auxiliar de Cozinha",
    empresa: "Vegas Burger",
    cidade: "Londrina",
    descricao: "Vaga de Auxiliar de Cozinha na Vegas Burger Hamburgueria (Shopping Norte). Início imediato com escala de revezamento 6x1!",
    descricaoModal:"Informações da Vaga: 1 vaga disponível para Auxiliar de Cozinha no Shopping Norte com início imediato. Escala de revezamento 6x1 com carga horária de 7:20h (turno das 14:40 às 23:00). Seleção presencial no dia 09 de Janeiro de 2026.",
    whatsapp: "5543933383030",
    email: "",
    banner: "banners/vegas.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Caixa",
    empresa: "Vegas Burger",
    cidade: "Londrina",
    descricao: "🍔 Vaga para Caixa na Vegas Burger Hamburgueria (Shopping Norte). Início imediato com escala 6x1 e ótimo ambiente de trabalho!",
    descricaoModal:"Informações da Vaga: 1 vaga disponível para o cargo de Caixa no Shopping Norte com início imediato. Escala de revezamento 6x1 com carga horária de 7:20h (turno das 14:40 às 23:00).",
    whatsapp: "5543933383030",
    email: "",
    banner: "banners/vegascx.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Atendente",
    empresa: "Gelaboca",
    cidade: "Londrina",
    descricao: "Vaga de Atendente na Gela Boca - Salário de R$ 2.500,00 + Benefícios. Venha fazer parte do time mais gelado e divertido da cidade!",
    descricaoModal:"Benefícios e Informações: Salário de R$ 2.500,00, Vale transporte, Vale alimentação e Bônus por desempenho. Se você se identificou com a vaga, mande seu currículo agora mesmo!",
    whatsapp: "5543999127431",
    email: "",
    banner: "banners/gelaboca.jpg"
  },
  {
    data: "2026-01-05",
    titulo: "Auxiliar de Limpeza",
    empresa: "Beta Serv",
    cidade: "Londrina",
    descricao: "Temos Vaga! Auxiliar de Limpeza na Beta Serv. Oportunidade para profissionais com experiência mínima na área e disponibilidade de horário.",
    descricaoModal:"Requisitos: Experiência mínima comprovada na função. Horário: Jornada semanal de 8h com necessidade de disponibilidade para trabalhar também aos fins de semana intercalados.",
    whatsapp: "5543988256040",
    email: "",
    banner: "banners/beta.jpg"
  },
  
  
];
